config:
  head: "&2--- ZoneMenu ---"
  head_extra: " &6(Options are clickable)"
  find: "&6>> Look for a free place."
  find_hover: "&6/zone find"
  sign: "&6>> Sign your new zone."
  sign_hover: "&6/zone sign"
  create: "&6>> Create your new zone."
  create_hover: "&6/zone create"
  cancel: "&6>> Cancel creation."
  cancel_hover: "&6/zone cancel"
  addmember: "&6>> Add a player to your zone."
  addmember_hover: "&6/zone addmember <Player>"
  removemember: "&6>> Remove a player from your zone."
  removemember_hover: "&6/zone removemember <Player>"
  info: "&6>> Get information about your zone."
  info_hover: "&6/zone info"
  delete: "&6>> Delete your zone."
  delete_hover: "&6/zone delete"
  zone_find: "&6Use the stick to look for a free place by &2left- &6and &2right-click&6."
  zone_sign: "&6Use the stick to sign the &5first &6point by &2left- &6and the &dsecond &6point by &2right-click&6."
  zone_create_already_have: "&4You already have a zone in this world."
  zone_create_not_signed: "&4Sign your zone first."
  zone_create_area_min: 100
  zone_create_area_max: 10000
  zone_create_area_under: "&4Minimum area: &6{0}"
  zone_create_area_over: "&4Maximum area: &6{0}"
  zone_create_overlaps_unowned: "&4Your zone overlaps with one or more unowned zones."
  zone_create_priority: 1
  zone_create: "&6Zone created."
  zone_cancel_not_running: "&4Zone creation not running."
  zone_cancel: "&6Zone creation cancelled."
  no_zone: "&4You do not have a zone in this world."
  zone_addmember_not_existing: "&4The player &6{0} &4does not exist."
  zone_addmember_already_member: "&4The player &6{0} &4is already a member of your zone."
  zone_addmember: "&6The player &2{0} &6is now a member of your zone."
  zone_removemember_unknownplayer: "&4The player &6{0} &4is not a member of your zone."
  zone_removemember: "&6The player &2{0} &6is no longer a member of your zone."
  zone_info_id: "&6ID: &2"
  zone_info_priority: "&6Priority: &2"
  zone_info_owners: "&6Owners: &2"
  zone_info_members: "&6Members: &2"
  zone_info_start: "&5Starting &6point: &2X: {0} &6/ &2Z: {1}"
  zone_info_end: "&dEnding &6point: &2X: {0} &6/ &2Z: {1}"
  zone_info_area: "&6Area: &2{0}"
  zone_delete: "&6Zone deleted."
  usage_message: "&4Please use &6{0}&4."
  permission_message: "&4You need &6{0}&4."
  event_find_multi: "&6Zones found: &2"
  event_find_no: "&4No zones found."
  event_find: "&6Zone found: &2"
  event_sign_first: "&5First &6position marked."
  event_sign_second: "&dSecond &6position marked."
  event_sign_area: " &6Area: &2{0}"
  zone_wait_message: "&2ZoneMenu &4- &6Please wait ..."
  console_message: "&4Console? &6No."