name: ZoneMenu
version: ${project.version}
description: ZoneMenu
author: joestr
authors: [Joe83, Joe84, 9YB]
website: https://repo.joestr.xyz/zonemenu

main: xyz.joestr.zonemenu.ZoneMenu
database: false
depend: [WorldEdit, WorldGuard]

commands:
  zone:
    description: List all possible sub-commands.
    #permission: zonemenu.*
    #permission-message: You need zonemenu.*.
    usage: Please use /zone.
    
permissions:
  zonemenu.*:
    description: Permission to list all possible sub-commands.
    default: true
    #children:
    #  zonemenu.*: true